-- ============================================================
--  Phase 2, tache 2.8 du plan PDG (n° 2.8 du CR de réunion) —
--  suivi des observations des coordinateurs.
--
--  Avant : les observations vivaient dans un bloc JSON de la colonne
--  texte op_points_journaliers.observations, sous la forme
--  [{"type":"alerte","texte":"..."}]. Les éléments n'ont ni identifiant
--  ni horodatage propre : ce format ne peut pas porter un statut par
--  observation, un responsable, ni un historique de relances.
--
--  Décision de reprise : on démarre à blanc. Les observations déjà
--  saisies restent lisibles dans leur point journalier mais n'entrent
--  pas dans le workflow — arbitrage rendu avec le métier, pour éviter
--  de remplir la file du superviseur d'observations anciennes et
--  probablement obsolètes.
--
--  La colonne JSON reste écrite par le point journalier : elle sert
--  toujours à réafficher les observations dans le formulaire et dans
--  la fiche PDF. Cette table porte le suivi, pas l'affichage. Les deux
--  restent alignés parce que l'enregistrement du point réécrit les
--  deux dans la même transaction.
--
--  UNIQUE (point_id, ordre) : les éléments du JSON n'ayant pas
--  d'identifiant, c'est leur position qui les identifie. La contrainte
--  rend toute reprise ultérieure rejouable sans créer de doublon.
--
--  Idempotente : IF NOT EXISTS, rejouable sans effet.
-- ============================================================
BEGIN;

CREATE TABLE IF NOT EXISTS public.op_observations (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id          integer NOT NULL REFERENCES public.op_points_journaliers(id) ON DELETE CASCADE,
    ordre             smallint NOT NULL,
    site_id           integer NOT NULL REFERENCES public.sites(id),
    type              varchar(20) NOT NULL,   -- info | alerte | relance | incident | urgence | autre
    texte             text NOT NULL,
    -- en_attente -> en_cours -> traite -> cloture ; escalade au-dela de 3 relances
    statut            varchar(20) NOT NULL DEFAULT 'en_attente',
    responsable_id    integer REFERENCES public.users(id),
    pris_en_charge_at timestamp,
    cloture_at        timestamp,
    commentaire       text,
    nb_relances       smallint NOT NULL DEFAULT 0,
    created_by        integer REFERENCES public.users(id),
    created_at        timestamp DEFAULT now(),
    CONSTRAINT op_observations_point_ordre_key UNIQUE (point_id, ordre)
);

-- Historique des relances : le CR demande la date et l'heure de chacune,
-- donc une table plutot qu'un simple compteur.
CREATE TABLE IF NOT EXISTS public.op_observation_relances (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observation_id integer NOT NULL REFERENCES public.op_observations(id) ON DELETE CASCADE,
    relance_at     timestamp DEFAULT now(),
    par_user_id    integer REFERENCES public.users(id)
);

-- La file de traitement se lit par statut, et le coordinateur suit les
-- siennes par site : ce sont les deux axes de lecture de l'ecran.
CREATE INDEX IF NOT EXISTS idx_obs_statut     ON public.op_observations (statut, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_obs_site       ON public.op_observations (site_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_obs_point      ON public.op_observations (point_id);
CREATE INDEX IF NOT EXISTS idx_obs_rel_obs    ON public.op_observation_relances (observation_id);

COMMIT;

-- Contrôle :
-- SELECT statut, COUNT(*) FROM op_observations GROUP BY statut;
