-- ============================================================
--  Migration MySQL : préférences d'affichage (vps-mysql)
-- ============================================================
--  Traduction de sql/migration_preferences_affichage.sql (branche main,
--  PostgreSQL) — 3 tables utilisées par pages/kpi_dashboard.php pour les
--  filtres mémorisés, les défauts par rôle et les vues enregistrées.
--
--  Différences avec l'original Postgres :
--   - `GENERATED BY DEFAULT AS IDENTITY` -> `AUTO_INCREMENT`
--   - `COMMENT ON TABLE/COLUMN` (instruction séparée, inexistante en
--     MySQL) -> attribut `COMMENT` inline sur la colonne/table
--   - index secondaire déclaré en ligne dans le CREATE TABLE plutôt
--     qu'un `CREATE INDEX IF NOT EXISTS` séparé, que MySQL ne supporte
--     pas (pas d'idempotence possible sur cette syntaxe côté MySQL)
--   - `VALUES (...) AS v(slug, periode)` -> sous-requête `UNION ALL`,
--     compatible avec les versions de MySQL/MariaDB antérieures à 8.0.19
--   - `ON CONFLICT (role_id, cle) DO NOTHING` -> `INSERT IGNORE`
--     (role_id, cle) est la clé primaire de defauts_affichage, donc le
--     comportement est identique : ligne déjà présente = ignorée.
--
--  ⚠️ Non vérifiée contre une vraie base MySQL de production
--  (indisponible au moment d'écrire ce fichier) — à confirmer avant la
--  mise en production, même principe que les autres migrations
--  "_mysql.sql" de cette branche.
--
--  Idempotente : CREATE TABLE IF NOT EXISTS + INSERT IGNORE, rejouable
--  sans effet de bord.
-- ============================================================

-- ══════════════════════════════════════════════════════════════
--  1. Préférences par utilisateur
-- ══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS `preferences_utilisateur` (
    `user_id`    int(10) UNSIGNED NOT NULL,
    `cle`        varchar(80) NOT NULL COMMENT 'Forme "<ecran>.<filtre>", ex. "kpi_dashboard.periode".',
    `valeur`     text NOT NULL,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`user_id`, `cle`),
    CONSTRAINT `preferences_utilisateur_user_fk`
        FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Filtres et réglages d''affichage mémorisés par utilisateur.';

-- ══════════════════════════════════════════════════════════════
--  2. Défauts d'affichage par rôle
-- ══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS `defauts_affichage` (
    `role_id`    int(10) UNSIGNED NOT NULL,
    `cle`        varchar(80) NOT NULL,
    `valeur`     text NOT NULL,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`role_id`, `cle`),
    CONSTRAINT `defauts_affichage_role_fk`
        FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Amorce alignée sur les profils de PRODUCT.md. Un rôle sans ligne
-- retombe sur le défaut du code : l'absence n'est pas une erreur.
INSERT IGNORE INTO `defauts_affichage` (`role_id`, `cle`, `valeur`)
SELECT r.id, 'kpi_dashboard.periode', v.periode
  FROM `roles` r
  JOIN (
        SELECT 'coordinateur_site'     AS slug, 'journalier'   AS periode
        UNION ALL SELECT 'gestionnaire_stock',    'hebdomadaire'
        UNION ALL SELECT 'superviseur_operation', 'hebdomadaire'
        UNION ALL SELECT 'gsb',                   'hebdomadaire'
        UNION ALL SELECT 'pdg',                   'mensuel'
        UNION ALL SELECT 'lecteur',               'mensuel'
       ) v ON v.slug = r.slug;

-- ══════════════════════════════════════════════════════════════
--  3. Vues enregistrées
-- ══════════════════════════════════════════════════════════════
--  `filtres` porte la query string du jeu de filtres (sites[]=3&periode=
--  hebdomadaire…) plutôt qu'un JSON typé : c'est exactement ce que la
--  page sait déjà relire, et une vue enregistrée reste ainsi valable si
--  un filtre s'ajoute plus tard.
CREATE TABLE IF NOT EXISTS `vues_enregistrees` (
    `id`         int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id`    int(10) UNSIGNED NOT NULL,
    `ecran`      varchar(60) NOT NULL,
    `nom`        varchar(80) NOT NULL,
    `filtres`    text NOT NULL,
    `partagee`   tinyint(1) NOT NULL DEFAULT 0
        COMMENT 'À 1, la vue est proposée à tous ceux qui peuvent lire l''écran. Le propriétaire reste seul à pouvoir la modifier ou la supprimer.',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `vues_enregistrees_user_ecran_nom` (`user_id`, `ecran`, `nom`),
    KEY `vues_enregistrees_ecran_idx` (`ecran`, `partagee`),
    CONSTRAINT `vues_enregistrees_user_fk`
        FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
