-- ============================================================
--  Préférences d'affichage : filtres mémorisés, défauts par rôle,
--  vues enregistrées.
--
--  Les filtres ne vivaient que dans l'URL : partageables, jamais
--  retenus. Chacun reposait ses filtres à chaque ouverture, et le
--  défaut était « tous les sites / mensuel » — qui ne correspond à
--  aucun des quatre profils décrits dans PRODUCT.md. Un coordinateur
--  veut sa journée sur son site, un superviseur la semaine sur vingt
--  et un sites, la direction le mois.
--
--  Trois tables plutôt qu'une, parce que les trois portées ont des
--  durées de vie et des droits différents : la préférence appartient à
--  l'utilisateur et le suit, le défaut appartient au rôle et se règle
--  en administration, la vue est un objet nommé qu'on partage.
--
--  Modèle clé/valeur volontaire, sur le patron d'achat_parametres déjà
--  en place : une colonne par filtre et par écran ne tiendrait pas, les
--  filtres différant d'un écran à l'autre et s'ajoutant avec le temps.
--
--  Idempotente : rejouable sans effet de bord.
-- ============================================================

-- ══════════════════════════════════════════════════════════════
--  1. Préférences par utilisateur
-- ══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS preferences_utilisateur (
    user_id    integer     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    cle        varchar(80) NOT NULL,
    valeur     text        NOT NULL,
    updated_at timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, cle)
);

COMMENT ON TABLE preferences_utilisateur IS
    'Filtres et réglages d''affichage mémorisés par utilisateur. Clé de la forme "<ecran>.<filtre>", ex. "kpi_dashboard.periode".';

-- ══════════════════════════════════════════════════════════════
--  2. Défauts d'affichage par rôle
-- ══════════════════════════════════════════════════════════════
--  Ce sur quoi un utilisateur tombe la première fois, avant d'avoir
--  touché le moindre filtre. C'est là que se joue le « qu'est-ce qui me
--  concerne » de PRODUCT.md.
CREATE TABLE IF NOT EXISTS defauts_affichage (
    role_id    integer     NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    cle        varchar(80) NOT NULL,
    valeur     text        NOT NULL,
    updated_at timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, cle)
);

-- Amorce alignée sur les profils de PRODUCT.md. Un rôle sans ligne
-- retombe sur le défaut du code : l'absence n'est pas une erreur.
INSERT INTO defauts_affichage (role_id, cle, valeur)
SELECT r.id, 'kpi_dashboard.periode', v.periode
  FROM roles r
  JOIN (VALUES
        ('coordinateur_site',      'journalier'),
        ('gestionnaire_stock',     'hebdomadaire'),
        ('superviseur_operation',  'hebdomadaire'),
        ('gsb',                    'hebdomadaire'),
        ('pdg',                    'mensuel'),
        ('lecteur',                'mensuel')
       ) AS v(slug, periode) ON v.slug = r.slug
    ON CONFLICT (role_id, cle) DO NOTHING;

-- ══════════════════════════════════════════════════════════════
--  3. Vues enregistrées
-- ══════════════════════════════════════════════════════════════
--  Un jeu de filtres nommé. `filtres` porte la query string du jeu
--  (sites[]=3&sites[]=7&periode=hebdomadaire…) plutôt qu'un JSON typé :
--  c'est exactement ce que la page sait déjà relire, et une vue
--  enregistrée reste ainsi valable si un filtre s'ajoute plus tard.
CREATE TABLE IF NOT EXISTS vues_enregistrees (
    id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ecran      varchar(60) NOT NULL,
    nom        varchar(80) NOT NULL,
    filtres    text        NOT NULL,
    partagee   smallint    NOT NULL DEFAULT 0,
    created_at timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, ecran, nom)
);

CREATE INDEX IF NOT EXISTS vues_enregistrees_ecran_idx
    ON vues_enregistrees (ecran, partagee);

COMMENT ON COLUMN vues_enregistrees.partagee IS
    'À 1, la vue est proposée à tous ceux qui peuvent lire l''écran. Le propriétaire reste seul à pouvoir la modifier ou la supprimer.';
