-- ============================================================
--  Migration MySQL : table op_endommagements manquante sur vps-mysql
-- ============================================================
--  Traduction de sql/migration_tracabilite_endommagements.sql (branche
--  main), restée sans équivalent MySQL lors des rattrapages précédents.
--  Sans elle, trois écrans plantent (table inconnue) :
--    - pages/operations/point_journalier.php (pop-up de déclaration),
--    - pages/tracabilite_endommagements.php,
--    - pages/kpi_dashboard.php (panneau « Fiabilité & pertes »).
--
--  Une ligne PAR FILM endommagé, pas par bobine : six films abîmés sur
--  une même bobine peuvent l'avoir été à six moments et pour six causes.
--  film_no est un rang stable au sein d'une bobine pour un point donné,
--  pas un identifiant physique. Le lien vers le point est en ON DELETE
--  CASCADE : la correction d'un point (DELETE puis ré-INSERT) ne doit pas
--  laisser de déclarations orphelines.
--
--  Traduction : GENERATED BY DEFAULT AS IDENTITY -> AUTO_INCREMENT ;
--  clés en int(10) UNSIGNED, comme les tables référencées dans
--  sql/stockapp.sql ; index DESC de Postgres -> index ordinaire (InnoDB
--  le parcourt dans les deux sens). Idempotente : IF NOT EXISTS.
--
--  ⚠️ Structure déduite du schéma Postgres, PAS vérifiée contre une vraie
--  base MySQL de production — même réserve que les autres migrations
--  « _mysql.sql » de cette branche.
-- ============================================================

CREATE TABLE IF NOT EXISTS `op_endommagements` (
  `id`           int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `point_id`     int(10) UNSIGNED NOT NULL,
  `bobine_id`    int(10) UNSIGNED DEFAULT NULL,
  `site_id`      int(10) UNSIGNED NOT NULL,
  `film_no`      smallint NOT NULL DEFAULT 1,
  `personne`     varchar(150) NOT NULL,
  `etape`        varchar(20)  NOT NULL COMMENT 'pose | impression | transport | stockage | autre',
  `cause`        varchar(30)  NOT NULL COMMENT 'manipulation | defaut_materiel | incident_externe | autre',
  `heure`        time DEFAULT NULL,
  `observations` text,
  `created_by`   int(10) UNSIGNED DEFAULT NULL,
  `created_at`   timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  -- Un film d'une bobine ne se déclare qu'une fois par point.
  UNIQUE KEY `op_endommagements_film_key` (`point_id`, `bobine_id`, `film_no`),
  KEY `idx_endo_site_date` (`site_id`, `created_at`),
  KEY `idx_endo_bobine` (`bobine_id`),
  CONSTRAINT `op_endommagements_point_fk`  FOREIGN KEY (`point_id`)   REFERENCES `op_points_journaliers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `op_endommagements_bobine_fk` FOREIGN KEY (`bobine_id`)  REFERENCES `op_bobines` (`id`),
  CONSTRAINT `op_endommagements_site_fk`   FOREIGN KEY (`site_id`)    REFERENCES `sites` (`id`),
  CONSTRAINT `op_endommagements_user_fk`   FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Contrôle :
-- SELECT COUNT(*) FROM op_endommagements;
