-- ============================================================
--  Migration MySQL : suivi des observations des points journaliers
-- ============================================================
--  Traduction de sql/migration_observations_suivi.sql (branche main),
--  restée sans équivalent MySQL : pages/observations.php et
--  l'enregistrement du point journalier plantaient (table inconnue).
--
--  op_observations : une ligne par observation saisie dans un point,
--  avec son cycle de vie (en_attente -> en_cours -> traite -> cloture,
--  escalade au-delà de trois relances). op_observation_relances garde
--  l'historique des relances.
--
--  Traduction : GENERATED BY DEFAULT AS IDENTITY -> AUTO_INCREMENT ;
--  clés en int(10) UNSIGNED comme dans sql/stockapp.sql ; index DESC et
--  CREATE INDEX IF NOT EXISTS -> index déclarés dans CREATE TABLE ;
--  `type` entre accents graves. Idempotente : IF NOT EXISTS.
--
--  ⚠️ Non vérifiée contre la vraie base MySQL de production — même
--  réserve que les autres migrations « _mysql.sql » de cette branche.
-- ============================================================

CREATE TABLE IF NOT EXISTS `op_observations` (
  `id`                int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `point_id`          int(10) UNSIGNED NOT NULL,
  `ordre`             smallint NOT NULL,
  `site_id`           int(10) UNSIGNED NOT NULL,
  `type`              varchar(20) NOT NULL COMMENT 'info | alerte | relance | incident | urgence | autre',
  `texte`             text NOT NULL,
  `statut`            varchar(20) NOT NULL DEFAULT 'en_attente',
  `responsable_id`    int(10) UNSIGNED DEFAULT NULL,
  `pris_en_charge_at` timestamp NULL DEFAULT NULL,
  `cloture_at`        timestamp NULL DEFAULT NULL,
  `commentaire`       text,
  `nb_relances`       smallint NOT NULL DEFAULT 0,
  `created_by`        int(10) UNSIGNED DEFAULT NULL,
  `created_at`        timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `op_observations_point_ordre_key` (`point_id`, `ordre`),
  KEY `idx_obs_statut` (`statut`, `created_at`),
  KEY `idx_obs_site` (`site_id`, `created_at`),
  CONSTRAINT `op_observations_point_fk`  FOREIGN KEY (`point_id`)       REFERENCES `op_points_journaliers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `op_observations_site_fk`   FOREIGN KEY (`site_id`)        REFERENCES `sites` (`id`),
  CONSTRAINT `op_observations_resp_fk`   FOREIGN KEY (`responsable_id`) REFERENCES `users` (`id`),
  CONSTRAINT `op_observations_auteur_fk` FOREIGN KEY (`created_by`)     REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `op_observation_relances` (
  `id`             int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `observation_id` int(10) UNSIGNED NOT NULL,
  `relance_at`     timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `par_user_id`    int(10) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_obs_rel_obs` (`observation_id`),
  CONSTRAINT `op_obs_relances_obs_fk`  FOREIGN KEY (`observation_id`) REFERENCES `op_observations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `op_obs_relances_user_fk` FOREIGN KEY (`par_user_id`)    REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
