-- ============================================================
--  Migration MySQL : référentiels de capacités (bobines, PMMA)
-- ============================================================
--  Traduction de sql/migration_referentiels_capacites.sql (branche
--  main), restée sans équivalent MySQL. Elle porte :
--    1. op_types_bobines.films_par_bobine — films d'une bobine neuve,
--       500 par défaut, 2000 pour les séries TL et WSL ;
--    2. la table op_types_pmma — catalogue des types de PMMA et de leur
--       conditionnement en cartons ;
--    3. le droit referentiels_operations pour admin et superadmin.
--  Utilisée par pages/admin/referentiels_operations.php,
--  includes/referentiels.php (création de bobine, projections) et
--  pages/simulation_stocks.php.
--
--  Traduction :
--    - ADD COLUMN IF NOT EXISTS -> information_schema + requête préparée
--      (MySQL 8 ne l'accepte pas) ;
--    - COMMENT ON COLUMN -> attribut COMMENT inline ;
--    - GENERATED BY DEFAULT AS IDENTITY -> AUTO_INCREMENT ;
--    - CREATE INDEX IF NOT EXISTS -> index déclaré dans CREATE TABLE ;
--    - ON CONFLICT (code) DO NOTHING -> INSERT IGNORE ;
--    - (regexp_match(...))[2] : MySQL ne rend pas de groupe capturé ; la
--      série est cherchée lettre par lettre (A, B, C, D), entourée d'un
--      caractère non alphabétique ou d'un bord de chaîne, après retrait
--      de « PMMA » — même règle que l'original ;
--    - VALUES (...) AS v(...) -> sous-requête UNION ALL ;
--    - || -> CONCAT().
--  Idempotente : rejouable sans effet.
--
--  ⚠️ Non vérifiée contre la vraie base MySQL de production — même
--  réserve que les autres migrations « _mysql.sql » de cette branche.
-- ============================================================

-- 1. Films par bobine, par type.
SET @existe := (SELECT COUNT(*) FROM information_schema.columns
                 WHERE table_schema = DATABASE()
                   AND table_name   = 'op_types_bobines'
                   AND column_name  = 'films_par_bobine');
SET @sql := IF(@existe = 0,
    'ALTER TABLE `op_types_bobines` ADD COLUMN `films_par_bobine` smallint NOT NULL DEFAULT 500
       COMMENT ''Nombre de films que contient une bobine neuve de ce type. Sert de valeur initiale à la création et de base aux projections.''',
    'SELECT ''films_par_bobine déjà présente'' AS info');
PREPARE etape FROM @sql;
EXECUTE etape;
DEALLOCATE PREPARE etape;

UPDATE op_types_bobines
   SET films_par_bobine = 2000
 WHERE TRIM(serie) IN ('TL', 'WSL')
   AND films_par_bobine = 500;

-- 2. Catalogue des types de PMMA.
CREATE TABLE IF NOT EXISTS `op_types_pmma` (
  `id`                int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code`              varchar(50)  NOT NULL,
  `libelle`           varchar(150) NOT NULL,
  `serie`             char(1) DEFAULT NULL,
  `unites_par_carton` smallint NOT NULL DEFAULT 25
      COMMENT 'Unités de PMMA contenues dans un carton. La saisie et le stock restent comptés en unités : cette valeur ne sert qu''à convertir un besoin en cartons à commander.',
  `seuil_defaut`      int NOT NULL DEFAULT 10,
  `actif`             smallint NOT NULL DEFAULT 1,
  `created_at`        timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `op_types_pmma_code_key` (`code`),
  KEY `op_types_pmma_actif_idx` (`actif`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Types réellement présents dans les stocks et les points journaliers.
INSERT IGNORE INTO op_types_pmma (code, libelle, serie, unites_par_carton, seuil_defaut)
SELECT code,
       CASE WHEN serie IS NULL THEN code ELSE CONCAT('PMMA type ', serie) END,
       serie,
       CASE WHEN serie = 'A' THEN 50 ELSE 25 END,
       10
  FROM (SELECT code,
               CASE WHEN nu REGEXP '(^|[^A-Z])A([^A-Z]|$)' THEN 'A'
                    WHEN nu REGEXP '(^|[^A-Z])B([^A-Z]|$)' THEN 'B'
                    WHEN nu REGEXP '(^|[^A-Z])C([^A-Z]|$)' THEN 'C'
                    WHEN nu REGEXP '(^|[^A-Z])D([^A-Z]|$)' THEN 'D'
               END AS serie
          FROM (SELECT code, REPLACE(UPPER(code), 'PMMA', '') AS nu
                  FROM (SELECT DISTINCT TRIM(type_pmma) AS code
                          FROM stock_pmma_site
                         WHERE COALESCE(TRIM(type_pmma), '') <> ''
                        UNION
                        SELECT DISTINCT TRIM(type_pmma)
                          FROM op_pmma_utilises
                         WHERE COALESCE(TRIM(type_pmma), '') <> '') observes) nettoyes) classes;

-- Base vide : les quatre séries de référence.
INSERT IGNORE INTO op_types_pmma (code, libelle, serie, unites_par_carton, seuil_defaut)
SELECT v.code, v.libelle, v.serie, v.cap, 10
  FROM (SELECT 'PMMA type A' AS code, 'PMMA type A' AS libelle, 'A' AS serie, 50 AS cap
        UNION ALL SELECT 'PMMA type B', 'PMMA type B', 'B', 25
        UNION ALL SELECT 'PMMA type C', 'PMMA type C', 'C', 25
        UNION ALL SELECT 'PMMA type D', 'PMMA type D', 'D', 25) v
 WHERE NOT EXISTS (SELECT 1 FROM op_types_pmma);

-- 3. Droit sur l'écran Référentiels & capacités.
INSERT INTO permissions (role_id, module, can_create, can_read, can_update, can_delete)
SELECT r.id, 'referentiels_operations',
       CASE WHEN r.slug IN ('admin','superadmin') THEN 1 ELSE 0 END,
       CASE WHEN r.slug IN ('admin','superadmin') THEN 1 ELSE 0 END,
       CASE WHEN r.slug IN ('admin','superadmin') THEN 1 ELSE 0 END,
       0
  FROM roles r
 WHERE NOT EXISTS (
        SELECT 1 FROM permissions p
         WHERE p.role_id = r.id AND p.module = 'referentiels_operations');
