-- ============================================================
--  Phase 2, tache 2.1 du plan PDG (n° 2.1 du CR de réunion) —
--  traçabilité structurée des bobines endommagées.
--
--  Avant : le point journalier ne retenait qu'un compteur,
--  op_films_utilises.films_endommages, par bobine. On savait combien
--  de films étaient perdus, jamais à quelle étape ni par qui.
--
--  Cette table porte une ligne PAR FILM endommagé, pas par bobine : six
--  films abîmés sur une même bobine peuvent l'avoir été à six moments,
--  par des personnes différentes et pour des causes différentes. Une
--  ligne par bobine portant une quantité écraserait ce détail, qui est
--  précisément ce que la traçabilité doit restituer.
--
--  film_no numérote les films au sein d'une bobine pour un point donné.
--  Ce n'est pas un identifiant physique du film — le système n'en a pas
--  — mais un rang stable qui permet l'unicité et la relecture.
--
--  Le lien vers le point est en ON DELETE CASCADE : le point journalier
--  possède ses déclarations, et son chemin de correction (DELETE puis
--  ré-INSERT de op_films_utilises) fait de même ici, sans quoi une
--  correction laisserait des déclarations orphelines pointant sur des
--  bobines qui ne sont plus dans le point.
--
--  site_id est dénormalisé depuis le point journalier : la traçabilité
--  se filtre d'abord par site, et le porter ici évite une jointure sur
--  chaque lecture de l'historique.
--
--  Idempotente : IF NOT EXISTS, rejouable sans effet.
-- ============================================================
BEGIN;

CREATE TABLE IF NOT EXISTS public.op_endommagements (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id      integer NOT NULL REFERENCES public.op_points_journaliers(id) ON DELETE CASCADE,
    bobine_id     integer REFERENCES public.op_bobines(id),
    site_id       integer NOT NULL REFERENCES public.sites(id),
    film_no       smallint NOT NULL DEFAULT 1,
    personne      varchar(150) NOT NULL,
    etape         varchar(20)  NOT NULL,  -- pose | impression | transport | stockage | autre
    cause         varchar(30)  NOT NULL,  -- manipulation | defaut_materiel | incident_externe | autre
    heure         time,
    observations  text,
    created_by    integer REFERENCES public.users(id),
    created_at    timestamp DEFAULT now(),
    -- Un film donné d'une bobine ne peut être déclaré qu'une fois par
    -- point : rend l'enregistrement rejouable sans créer de doublon.
    CONSTRAINT op_endommagements_film_key UNIQUE (point_id, bobine_id, film_no)
);

-- L'historique se consulte filtré par site et par période : c'est le
-- couple qui porte la charge de lecture du nouveau module.
CREATE INDEX IF NOT EXISTS idx_endo_site_date  ON public.op_endommagements (site_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_endo_point      ON public.op_endommagements (point_id);
CREATE INDEX IF NOT EXISTS idx_endo_bobine     ON public.op_endommagements (bobine_id);

COMMIT;

-- Contrôle :
-- SELECT COUNT(*) FROM op_endommagements;
