-- ============================================================
--  Capacités de conditionnement : films par bobine, unités par carton PMMA
--
--  Ces deux valeurs étaient écrites en dur dans le code — 500 films dans
--  l'INSERT de operations/bobines.php, la règle « WSL/TL = 2000, sinon
--  500 » recopiée à l'identique dans import_bobines.php et
--  import_emuci.php, et rien du tout pour le PMMA. Un changement de
--  conditionnement fournisseur demandait donc un déploiement.
--
--  Elles rejoignent le référentiel de type, là où le schéma range déjà ce
--  genre de paramètre : op_types_vehicule porte nb_plaques et nb_rivets
--  depuis l'origine. Une table clé/valeur à la achat_parametres ne
--  convenait pas : la valeur dépend du type, on aurait fabriqué des clés
--  pmma_A_capacite, pmma_B_capacite… c'est-à-dire une table déguisée.
--
--  Idempotente : rejouable sans effet de bord.
-- ============================================================

-- ══════════════════════════════════════════════════════════════
--  1. Films par bobine, sur le catalogue des types de bobines
-- ══════════════════════════════════════════════════════════════
ALTER TABLE op_types_bobines
    ADD COLUMN IF NOT EXISTS films_par_bobine smallint NOT NULL DEFAULT 500;

-- Les séries Réservoir (TL) et Pare-brise (WSL) sont conditionnées par
-- 2000. On ne touche que les lignes encore au défaut : si un
-- administrateur a déjà corrigé une valeur par l'écran, la rejouer ne
-- doit pas l'écraser.
UPDATE op_types_bobines
   SET films_par_bobine = 2000
 WHERE TRIM(serie) IN ('TL', 'WSL')
   AND films_par_bobine = 500;

COMMENT ON COLUMN op_types_bobines.films_par_bobine IS
    'Nombre de films que contient une bobine neuve de ce type. Sert de valeur initiale à la création et de base aux projections.';

-- ══════════════════════════════════════════════════════════════
--  2. Catalogue des types de PMMA
-- ══════════════════════════════════════════════════════════════
--  Jusqu'ici stock_pmma_site.type_pmma était du texte libre : chaque
--  saisie créait un type, d'où des variantes de casse pour une même
--  matière. Le catalogue devient la référence, et son `code` reprend
--  EXACTEMENT la valeur utilisée dans les stocks : sans cela il faudrait
--  réécrire type_pmma partout, y compris dans l'historique de
--  op_pmma_utilises et stock_pmma, pour un gain nul.
CREATE TABLE IF NOT EXISTS op_types_pmma (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               varchar(50)  NOT NULL UNIQUE,
    libelle            varchar(150) NOT NULL,
    serie              char(1),
    unites_par_carton  smallint     NOT NULL DEFAULT 25,
    seuil_defaut       integer      NOT NULL DEFAULT 10,
    actif              smallint     NOT NULL DEFAULT 1,
    created_at         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN op_types_pmma.unites_par_carton IS
    'Unités de PMMA contenues dans un carton. La saisie et le stock restent comptés en unités : cette valeur ne sert qu''à convertir un besoin en cartons à commander.';

-- Reprise des types déjà présents dans les stocks. La série se déduit de
-- la dernière lettre A–D rencontrée dans le libellé ; le carton vaut 50
-- pour la série A, 25 pour B, C et D. Un type dont la série reste
-- indéterminée prend 25 et devra être corrigé à l'écran — c'est visible,
-- contrairement à un défaut silencieux.
WITH observes AS (
    SELECT DISTINCT TRIM(type_pmma) AS code
      FROM stock_pmma_site
     WHERE COALESCE(TRIM(type_pmma), '') <> ''
    UNION
    SELECT DISTINCT TRIM(type_pmma)
      FROM op_pmma_utilises
     WHERE COALESCE(TRIM(type_pmma), '') <> ''
), classes AS (
    -- On cherche une lettre A–D ISOLÉE, une fois le mot PMMA retiré :
    -- sans cette précaution le « A » de PMMA ferait passer n'importe quel
    -- libellé pour de la série A, et « Standard » en serait un.
    SELECT code,
           (regexp_match(
                UPPER(regexp_replace(code, 'PMMA', '', 'gi')),
                '(^|[^A-Z])([ABCD])([^A-Z]|$)'))[2] AS serie
      FROM observes
)
INSERT INTO op_types_pmma (code, libelle, serie, unites_par_carton, seuil_defaut)
SELECT code,
       CASE WHEN serie IS NULL THEN code ELSE 'PMMA type ' || serie END,
       serie,
       CASE WHEN serie = 'A' THEN 50 ELSE 25 END,
       10
  FROM classes
    ON CONFLICT (code) DO NOTHING;

-- Si aucun stock PMMA n'existe encore, le catalogue serait vide et
-- l'écran de paramétrage sans objet : on amorce les quatre types
-- standard. ON CONFLICT protège les installations déjà pourvues.
INSERT INTO op_types_pmma (code, libelle, serie, unites_par_carton, seuil_defaut)
SELECT v.code, v.libelle, v.serie, v.cap, 10
  FROM (VALUES
        ('PMMA type A', 'PMMA type A', 'A', 50),
        ('PMMA type B', 'PMMA type B', 'B', 25),
        ('PMMA type C', 'PMMA type C', 'C', 25),
        ('PMMA type D', 'PMMA type D', 'D', 25)
       ) AS v(code, libelle, serie, cap)
 WHERE NOT EXISTS (SELECT 1 FROM op_types_pmma)
    ON CONFLICT (code) DO NOTHING;

CREATE INDEX IF NOT EXISTS op_types_pmma_actif_idx ON op_types_pmma (actif);

-- ══════════════════════════════════════════════════════════════
--  3. Permissions du nouvel écran de paramétrage
-- ══════════════════════════════════════════════════════════════
--  Ouvert en lecture/écriture aux seuls profils d'administration : une
--  capacité fausse se propage à toutes les projections, ce n'est pas un
--  réglage d'exploitation. Les autres rôles reçoivent une ligne à zéro
--  plutôt que rien, pour que l'écran Permissions puisse l'afficher.
INSERT INTO permissions (role_id, module, can_create, can_read, can_update, can_delete)
SELECT r.id, 'referentiels_operations',
       CASE WHEN r.slug IN ('admin','superadmin') THEN 1 ELSE 0 END,
       CASE WHEN r.slug IN ('admin','superadmin') THEN 1 ELSE 0 END,
       CASE WHEN r.slug IN ('admin','superadmin') THEN 1 ELSE 0 END,
       0
  FROM roles r
 WHERE NOT EXISTS (
        SELECT 1 FROM permissions p
         WHERE p.role_id = r.id AND p.module = 'referentiels_operations');
